baseURL = 'https://sangifer.github.io/'
languageCode = 'de-DE'
title = 'sangifer'
theme =  'ananke'
resourceDir = 'media'

defaultContentLanguage = "de"
sectionPagesMenu = "main"
enableRobotsTXT = true

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[languages.de]
contentDir = "content"
languageCode = 'de-DE'
weight = 2
title = 'sangifer'

[languages.en]
contentDir = "content"
languageCode = 'en-UK'
weight = 2
title = 'sangifer'

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = "exumo"
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 3
body_classes = "noto bg-near-white"
post_content_classes = "noto bg-near-white"
# read_more_copy = "läs hygg!"

[params.ananke.social.share]
networks = [
#  "email",
#  "facebook",
#  "bluesky",
#  "linkedin",
  "mastodon",
  "instagram"
]

[params.ananke.social.follow]
networks = [
 # "facebook",
 # "bluesky",
 # "linkedin",
  "mastodon",
  "instagram"
]

[params.ananke.social.mastodon]
username = "@exumo@norden.social"
# profilelink = "https://norden.social/@exumo"

[params.ananke.social.instagram]
username = "tangifer"